#!/bin/bash
echo '-=-=-=-=-=-=-=-=-=-'

if [ $1 ]; then

	if [ $1 = 'network-restart' ]; then
		echo 'Shutting Down Network...'
		sudo netctl stop harrhy
		echo 'Network Shutdown, Starting Network...'
		sudo netctl start harrhy
		echo 'Network Shutdown'

	elif [ $1 = 'startup' ]; then
		echo 'Starting Display...'
		xrandr --output VGA1 --primary
		xrandr -s 640x480
		xrandr -s 1920x1080
		echo 'Finished Display!'
		echo ''

		echo 'Starting Network...'
		sudo netctl start harrhy
		echo 'Finished Network!'

	else
		echo 'Unknown Command :('
	fi

else
	printf '  startup\n  network-restart\n'
fi

echo '-=-=-=-=-=-=-=-=-=-'
