#!/bin/bash
#
# ACCOUNTS FOR
#  bashrc-arch
#  bashrc-ubuntu
#  bashrc-universal
#
#  vimrc
#
#  autostart
#  xdefaults
#
#  doit

function arch() {
	cat ./bashrc-arch ./bashrc-universal > ~/.bashrc
	cat ./doit > ~/doit
}

function ubuntu() {
	cat ./bashrc-ubuntu ./bashrc-universal > ~/.bashrc
}

function universal() {
	cat vimrc > ~/.vimrc
	cat autostart > ~/.config/herbstluftwm/autostart
	cat xdefaults > ~/.Xdefaults
}

function inform() {
	echo '  replace-arch'
	echo '  replace-ubuntu'
}

if [ $1 ]; then
	case $1 in
		replace-arch)
			arch
			universal
			;;

		replace-ubuntu)
			ubuntu
			universal
			;;

		*)
			inform
	esac

else
	inform
fi
