" Vundle
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
	Plugin 'gmarik/Vundle.vim' 

        " Git
        Plugin 'tpope/vim-fugitive'

        " Status Bar
        Plugin 'vim-airline/vim-airline'
        Plugin 'vim-airline/vim-airline-themes'

	" File Management
	Plugin 'scrooloose/nerdtree'

	" Color Schemes
	Plugin 'flazz/vim-colorschemes'

	" Autocompletion
	Plugin 'ajh17/VimCompletesMe'

	" Markdown
        Plugin 'godlygeek/tabular'
	Plugin 'tpope/vim-markdown'

	" HTML
	Plugin 'digitaltoad/vim-pug'

	" CSS
	Plugin 'groenewege/vim-less'
	Plugin 'ap/vim-css-color'

	" Javascript/JSON
	Plugin 'elzr/vim-json'
	Plugin 'pangloss/vim-javascript'
	Plugin 'mxw/vim-jsx'
call vundle#end()
filetype plugin indent on

" JSX on .js
let g:jsx_ext_required = 0

" Indenting
set softtabstop=2
set shiftwidth=2
set expandtab

" Line Numbering
set number

" Syntax
syntax on
colorscheme devbox-dark-256

" Visual bell
:set visualbell

" Use ctrl-[hjkl] to select the active split
nmap <silent> <c-k> :wincmd k<CR>
nmap <silent> <c-j> :wincmd j<CR>
nmap <silent> <c-h> :wincmd h<CR>
nmap <silent> <c-l> :wincmd l<CR>

" Better wrapping on :set nowrap
:set textwidth=0
:set wrapmargin=0

" Python3 syntax checker
let g:syntastic_python_python_exec = '/usr/bin/python3'

" Vim-Airline Theme
let g:airline_theme='bubblegum'

" Automatic NERDTree Startup
"autocmd vimenter * NERDTree
