" Vundle
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
	Plugin 'gmarik/Vundle.vim' 

	" Syntax
	Plugin 'flazz/vim-colorschemes'

	" Git
	Plugin 'tpope/vim-fugitive'

	" Autocompletion
	Plugin 'ajh17/VimCompletesMe'

	" Reformatting
	Plugin 'godlygeek/tabular'

	" Markdown
	Plugin 'tpope/vim-markdown'

	" HTML
	Plugin 'digitaltoad/vim-pug'

	" CSS
	Plugin 'groenewege/vim-less'
	Plugin 'ap/vim-css-color'

	" Javascript/JSON
	Plugin 'Shutnik/jshint2.vim'
	Plugin 'elzr/vim-json'
	Plugin 'pangloss/vim-javascript'
call vundle#end()
filetype plugin indent on

" Indenting
setlocal shiftwidth=2
setlocal tabstop=2

" Line Numbering
set number

" Syntax
syntax on
colorscheme desert

" Visual bell
:set visualbell

" \vs Splits panes, with scrollock
:noremap <silent> <Leader>vs :<C-u>let @z=&so<CR>:set so=0 noscb<CR>:bo vs<CR>Ljzt:setl scb<CR><C-w>p:setl scb<CR>:let &so=@z<CR>

" Use ctrl-[hjkl] to select the active split
nmap <silent> <c-k> :wincmd k<CR>
nmap <silent> <c-j> :wincmd j<CR>
nmap <silent> <c-h> :wincmd h<CR>
nmap <silent> <c-l> :wincmd l<CR>

" Better wrapping on :set nowrap
:set textwidth=0
:set wrapmargin=0

" Python3 syntax checker
let g:syntastic_python_python_exec = '/usr/bin/python3'
